/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'readyForPickup' : IDL.Null,
  'preparing' : IDL.Null,
  'ordered' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'timestamp' : IDL.Nat,
  'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});

export const idlService = IDL.Service({
  'changeStaffPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Text], [OrderStatus], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [IDL.Text],
      [],
    ),
  'staffLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'staffUpdateOrderStatus' : IDL.Func(
      [IDL.Text, OrderStatus, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'readyForPickup' : IDL.Null,
    'preparing' : IDL.Null,
    'ordered' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'timestamp' : IDL.Nat,
    'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  
  return IDL.Service({
    'changeStaffPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Text], [OrderStatus], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [IDL.Text],
        [],
      ),
    'staffLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'staffUpdateOrderStatus' : IDL.Func(
        [IDL.Text, OrderStatus, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };